---
# handlers file for httpd_vhost
- name: reload service if configured
  service:
    name: httpd
    state: restarted
  listen: httpd_configured
- name:
  shell: |
    restorecon -R /var/www
  listen: httpd_configured
